export enum BlockType {
  TITLE = 'TITLE',
  TEXT = 'TEXT',
  CODE = 'CODE',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  FILL_GAPS = 'FILL_GAPS',
  DRAG_AND_MATCH = 'DRAG_AND_MATCH',
  ORDER_LINES = 'ORDER_LINES',
  TABLE_MIXED_CONTENT = 'TABLE_MIXED_CONTENT',
  MIXED_INLINE = 'MIXED_INLINE',
}
